name: setup

on:
  workflow_call
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v4
    - name: set up terraform
      uses: hashicorp/setup-terraform@v1
    - name: Initialize
      run: terraform init
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: test.tf
        path: test.tf
