name: checkov
on:
  workflow_call:

jobs:
   scan:
    permissions:
      contents: read 
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read 
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: test.tf

      - run: terraform format --check
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
        

        
       
